module.exports = {
  TYPE_MODE: "mode",
  TYPE_MODE_GROUP: "modeGroup",
  TYPE_DIGITS: "digits",
  TYPE_CORNER_MARKS: "cornerMarks",
  TYPE_CENTRE_MARKS: "centreMarks",
  TYPE_COLOURS: "colours",
  TYPE_PENLINES: "penLines",
  TYPE_SELECTION: "selection",
  TYPE_UNDO: "undo",
  TYPE_REDO: "redo",
  TYPE_INIT: "init",
  TYPE_CHECK: "check",
  TYPE_PAUSE: "pause",

  ACTION_ALL: "all",
  ACTION_SET: "set",
  ACTION_PUSH: "push",
  ACTION_CLEAR: "clear",
  ACTION_REMOVE: "remove",
  ACTION_ROTATE: "rotate",
  ACTION_RIGHT: "right",
  ACTION_LEFT: "left",
  ACTION_UP: "up",
  ACTION_DOWN: "down"
}
